---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install ansible
  - pip install 'molecule[docker]'

script:
  - molecule test --scenario-name github --debug

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
