---

- name: "common | version"
  debug:
    msg: "{{ zabbix_repo_version }} will be installed"

- name: "common | download package"
  get_url:
    url: "{{ zabbix_repo_packages[zabbix_repo_version] }}"
    dest: "{{ zabbix_repo_cache_dir }}/{{ zabbix_repo_package_name }}"
  delegate_to: localhost
  become: no
