---

- name: "Common | version"
  ansible.builtin.debug:
    msg: "{{ zabbix_repo_version }} will be installed"

- name: "Common | download package"
  ansible.builtin.get_url:
    url: "{{ zabbix_repo_packages[zabbix_repo_version] }}"
    dest: "{{ zabbix_repo_cache_dir }}/{{ zabbix_repo_version }}_{{ zabbix_repo_package_name }}"
    mode: 0664
  delegate_to: localhost
  become: false
