---
# tasks file for zabbix-repo

- name: "Common | set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags:
    - always

- name: "Include version set tasks"
  ansible.builtin.include_tasks: common-version.yml
  tags:
    - zabbix-repo
    - zabbix-repo:version
    - zabbix-repo:download
    - zabbix-repo:packages
  when: zabbix_repo_supported

- name: "Include download package tasks"
  ansible.builtin.include_tasks: common-download.yml
  tags:
    - zabbix-repo
    - zabbix-repo:version
    - zabbix-repo:download
  when: zabbix_repo_supported

- name: "Include packages common tasks"
  ansible.builtin.include_tasks: packages-common.yml
  tags:
    - zabbix-repo
    - zabbix-repo:packages
  when: zabbix_repo_supported

- name: "Include packages os tasks"
  ansible.builtin.include_tasks: packages-{{ ansible_os_family }}.yml
  tags:
    - zabbix-repo
    - zabbix-repo:packages
  when: zabbix_repo_supported
