---
# tasks file for zabbix-repo

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "os-{{ ansible_distribution }}.yml"
   - "os-default.yml"
  tags:
    - zabbix-repo


- name: "run os specific tasks"
  include: "{{ task_item }}"
  with_items: "{{ zabbix_repo_tasks }}"
  loop_control:
    loop_var: task_item
  tags:
    - zabbix-repo
