---
# tasks file for zabbix-repo

- name: "Common | set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags:
    - always

- name: "Include version set tasks"
  ansible.builtin.include_tasks:
    file: common-version.yml
    apply:
      tags:
        - zabbix-repo
        - zabbix-repo:version
        - zabbix-repo:download
        - zabbix-repo:packages
  when: zabbix_repo_supported
  tags:
    - always

- name: "Include download package tasks"
  ansible.builtin.include_tasks:
    file: common-download.yml
    apply:
      tags:
        - zabbix-repo
        - zabbix-repo:version
        - zabbix-repo:download
  when: zabbix_repo_supported
  tags:
    - always

- name: "Include packages common tasks"
  ansible.builtin.include_tasks:
    file: packages-common.yml
    apply:
      tags:
        - zabbix-repo
        - zabbix-repo:packages
  when: zabbix_repo_supported
  tags:
    - always

- name: "Include packages os tasks"
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - zabbix-repo
        - zabbix-repo:packages
  when: zabbix_repo_supported
  tags:
    - always
