---
- name: "debian | install package"
  ansible.builtin.apt:
    deb: "{{ zabbix_repo_tmp_dir }}/{{ zabbix_repo_package_name }}"
    dpkg_options: 'force-confnew,force-confdef'
  register: install

- name: "debian | update package cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  when: install is changed
