---
- name: "debian | install package"
  apt:
    deb: "{{ zabbix_repo_tmp_dir }}/{{ zabbix_repo_package_name }}"
    dpkg_options: 'force-confnew,force-confdef'
  register: install

- name: "debian | update package cache"
  apt:
    update_cache: yes
    cache_valid_time: 0
  when: install|changed
