---
dependency:
  name: galaxy
  enabled: True
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: debian-10
    image: debian:10
  - name: ubuntu-20.04
    image: ubuntu:20.04
  - name: centos-8
    image: centos:8
provisioner:
  name: ansible
verifier:
  name: ansible
  enabled: False
