---
dependency:
  name: galaxy
  enabled: True
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: debian-11
    image: debian:11
  - name: ubuntu-22.04
    image: ubuntu:22.04
  - name: rockylinux-8
    image: rockylinux:8
provisioner:
  name: ansible
  options:
    vvv: True
verifier:
  name: ansible
  enabled: False
